{% set name = "pyinstrument" %}
{% set version = "2.1.1" %}
{% set bundle = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_val = "b63cb9043babae952ed53558c308ff0b93f0e79f0fa49a5e6c17a5ed77061d3e" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  {{ hash_type }}: {{ hash_val }}

build:
  noarch: python
  entry_points:
    - pyinstrument = pyinstrument.__main__:main

  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
    - setuptools

  run:
    - python
    - pyinstrument_cext

test:
  imports:
    - pyinstrument

  commands:
    - pyinstrument --help

about:
  home: https://github.com/joerick/pyinstrument
  license: BSD 3-Clause
  license_file: {{ RECIPE_DIR }}/LICENSE
  license_family: BSD
  summary: "A call stack profiler for Python. Inspired by Apple's Instruments.app"
  dev_url: https://github.com/joerick/pyinstrument

extra:
  recipe-maintainers:
    - pmlandwehr
    - moorepants
