{% set name = "pyinstrument" %}
{% set version = "3.1.2" %}
{% set bundle = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_val = "14b260a7928185fd8b34429c73c4f88d80744b6b67731b093d31db8bfd1bf6b8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  {{ hash_type }}: {{ hash_val }}

build:
  noarch: python
  entry_points:
    - pyinstrument = pyinstrument.__main__:main

  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
    - pytest-runner
    - nodejs

  run:
    - python
    - pyinstrument_cext >=0.2.2

test:
  imports:
    - pyinstrument

  commands:
    - pyinstrument --help

about:
  home: https://github.com/joerick/pyinstrument
  license: BSD 3-Clause
  license_file: LICENSE
  license_family: BSD
  summary: "A call stack profiler for Python. Inspired by Apple's Instruments.app"
  dev_url: https://github.com/joerick/pyinstrument

extra:
  recipe-maintainers:
    - pmlandwehr
    - moorepants
    - asmeurer
