{% set name = "pyinstrument" %}
{% set version = "2.0.3" %}
{% set bundle = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_val = "100eed3db3e8b54ba3e175db27f92a75e8226e366f68b71612935ead49738b21" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  {{ hash_type }}: {{ hash_val }}

build:
  noarch: python
  entry_points:
    - pyinstrument = pyinstrument.__main__:main

  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
    - setuptools

  run:
    - python
    - pyinstrument_cext

test:
  imports:
    - pyinstrument

  commands:
    - pyinstrument --help

about:
  home: https://github.com/joerick/pyinstrument
  license: BSD 3-Clause
  license_file: {{ RECIPE_DIR }}/LICENSE
  license_family: BSD
  summary: "A call stack profiler for Python. Inspired by Apple's Instruments.app"
  dev_url: https://github.com/joerick/pyinstrument

extra:
  recipe-maintainers:
    - pmlandwehr
    - moorepants
