travis:
  secure:
    BINSTAR_TOKEN: MCd0WwkVGbLxqT5VdYFL33Io9bhfseSMPBFQkxrK9Hv+C0m90z2cHJ9pis9nV8psEuJyBKuGi0MrYuYcaLyS4AcjxPumpBWzNv8/pQ2X/VZSWDoxqxVU7XiTin00JzSVBStZCXnCQvzbp/3m3r/3AXg6cSfa2YIc4OfhHZAn/YzUK/2Z5X/2NN+W3crDPyUsdM95aq+6p9GZbINfWshozVePPiDUKR7QbNy1vuMWmHQEB5BkOFQCUeZSbEZ1U/uq9umPkZo3BCljuXpi0MSTeL0n6EtDsxeOxb8XtQMGn5IzMh/cM/gnpP/HbQe47F7NbMB4TfkqH/cmX1aS/d6IRi0zSUHGd8NNFEpL8CjmozJZg9RRcfPNhBqGqylXUOtn7ziYXt9ue2S5t40c9X3gaDfxvj/mBjka+et2prNSBaZUsuffy4mFk7D0SgunZv1XP5+5EHY9fEGZP0tT7BFMAP/ACiWzElMQF9vHLnlZsVVwr71+24IzP2VBNVV8YBn1XoAFyKxYEvexWZoPROuG1Ll/xzmLcCx0RsR2v1AkMGrZWg+e71bQr/yoJSi0AoktgJRq7q3STGHHluikYKZUm+vGWt8e7PeB2pIrSwjzcgv7+5iRKkShv7kChKQ/J7/YkuRFlMgYBdd519aZgjoMeWCFj/JRn2UITibC31Ikf34=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
