travis:
  secure:
    BINSTAR_TOKEN: ewaFnMYODtBQF/h4vMfE0ZmIu6ErI+pEdX1lEkrAlArfyQosuwTx8YtNGofHN0it8+pLb5sHaVRwXvVfsO0dTfIB550Jclvr5cKBpIAMWzXrjtMpFooHQlsS7mLme8ZkGvSaDzJXESMEpYWLM8yslzBngiGQcDf/2XcBWgh4FpDVaGe07LmC0DJkGdOibP3vklU9v5PPJD4r45l4fHb3h458xl6e5Woc79llWlDN/yyBQPlbLmd80nuozWYyCHYk2DLUCMP6VfYmmx341HbD9PR2OuPToIkD2CuQ4MhjiMSt5NibO+DRIyQqeYJhPTix/mxvXOVRY4RWNmGFZsHWeTdAFpP4gxvCh+tYjpfWdeYRSPi+gpZanimB+LTerCLuMJW/768SjQJJALw80Bq0bTHmZDrzUB9AeSq27dLwkR6jq+sPf/jv41TurJUvNbm7zy9m38UIdcfdrIPysg0PyMId8zEzJEFF1PChoEvTcc+APNSt/ULMpTJj8y3ClqAUx6c5y++PlUKtmdQNMTG/0PmQHwc0QXgkF44HyHSJ9dsy06+YzEIhiF/iDFYmAoMruhL4Nz42eEcWySsXiApg+yLnKIqqb2YBcIKIZut1aWvdpOZbZLwHx6kLCIoC/2+R1RUe6Bou8QKoe9YnKfjdtro5EBmyp51WE3EcvuPYq1o=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
