travis:
  secure:
    BINSTAR_TOKEN: pUww5QZrN6V4QWhw4yMpz6ocaeGCUeZk7Hrg9HnPI+NUB69l3D/jutVs6Lvx5KENXBEBe98GS/QShy7eJH+pampjuCP7ckx11rX/JtdYetGOH0OdVL6efxBzDOFKGMtwn0PPzg97GD8qHpUKTVdhVAkvwfovXA8/uqW2Nsqk1z+bwtU5M9els14HX0s4F+CAZdXKs13/CHwIY0i5aqUZcZrtxz4ZEu1CeFnnFBErW0NUiSRZ6elCom+QCT6tknTH/Plamru4NhuPkatPmzKThoohpquQ5RKPHhBdF1Bbafhtp/uU5zYGwU1Cr8th23Qiw21Lot9baNbK73RLBy6lkUmFm5MEnUMxKsZp9UKZiJ3ZW8HF9pmeTtUF17WRNBC0WSKrzq+WoUzRAQ2v/84EsqY/oZHmLXwQlCTRtpue8CgEhQ1zYi5ftdFC90PS9mNWu4llGE1huhvba/jy1I2ZuwzGbcYA9F0pQCYgHZDhvdd/QvV74VeZ9t/vKVXTduXGJuoObhE8LTVZtjD3N9blizXKiEkc5okTl6P8yInS6fTBEGfxHZ7fq4YT6Oagg7qxCt6KHOm+8Vp7NGyyx19EiklG/P/gGJ0LbH8ZMHvKy5FCYWA0CrGLZrdcDuRzGtmcWyTs/hHoCUJoLY+DmVaHo5vawRsPp5d9Gn3Tgmww3Hg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
